language: go

sudo: false

go:
  - 1.4.x
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x

before_install:
  - go get github.com/WindomZ/go-commander
  - go get github.com/WindomZ/testify/assert

install:
  - go install

script:
  - go test -v ./...
